[[langs]]
name = "brainfuck"
code = "brainfuck"
page = "http://esolangs.org/wiki/brainfuck"

[[langs]]
name = "Ook!"
code = "ook"
page = "http://esolangs.org/wiki/Ook"

[[langs]]
name = "triad"
code = "triad"
page = "https://esolangs.org/wiki/Triad"
